'use client'

import { Download } from 'lucide-react'

export default function GalleryCard({ url }: { url: string }) {
  const handleDownload = async () => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const file = new File([blob], 'supernexus_gallery.jpg', { type: blob.type || 'image/jpeg' });

      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth < 768;

      if (isMobile && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'SuperNexus',
          text: 'Generated by SuperNexus AI'
        });
      } else {
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'supernexus_image.jpg';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(link.href);
      }
    } catch (err) {
      console.error('Error downloading:', err);
    }
  };

  return (
    <div className="glass-panel hover-glow" style={{ padding: '1rem', borderRadius: '16px', overflow: 'hidden' }}>
      <img 
        src={url} 
        alt="AI Generated Output" 
        style={{ width: '100%', height: 'auto', borderRadius: '8px', display: 'block' }} 
      />
      <div style={{ marginTop: '1rem', display: 'flex', justifyContent: 'center' }}>
        <style>{`
          .dl-label-desktop { display: inline; }
          .dl-label-mobile { display: none; }
          @media (max-width: 768px) {
            .dl-label-desktop { display: none; }
            .dl-label-mobile { display: inline; }
          }
        `}</style>
        <button 
          onClick={handleDownload}
          className="btn-secondary"
          style={{ border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', width: '100%', padding: '0.75rem', cursor: 'pointer', fontWeight: 600 }}
        >
          <Download size={18} />
          <span className="dl-label-desktop">Download Image</span>
          <span className="dl-label-mobile">Save to Phone</span>
        </button>
      </div>
    </div>
  )
}
