'use client'

import { Download } from 'lucide-react'

export default function GalleryCard({ url, path }: { url: string, path?: string }) {
  const handleDownload = async () => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const file = new File([blob], 'supernexus_gallery.jpg', { type: blob.type || 'image/jpeg' });

      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth < 768;

      if (isMobile && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'SuperNexus',
          text: 'Generated by SuperNexus AI'
        });
      } else {
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'supernexus_image.jpg';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(link.href);
      }
    } catch (err) {
      console.error('Error downloading:', err);
    }
  };

  return (
    <div style={{ padding: '1rem', borderRadius: '24px', overflow: 'hidden', display: 'flex', flexDirection: 'column', gap: '0.75rem', background: '#1c1c1e', border: '1px solid rgba(255,255,255,0.05)', boxShadow: '0 10px 30px rgba(0,0,0,0.5)' }}>
      {path && (
        <div style={{ fontSize: '0.75rem', fontWeight: 600, color: '#D4AF37', letterSpacing: '0.05em', padding: '0.3rem 0.6rem', background: 'rgba(212, 175, 55, 0.1)', borderRadius: '6px', alignSelf: 'flex-start', textTransform: 'uppercase' }}>
          {path}
        </div>
      )}
      <div style={{ borderRadius: '16px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.1)', position: 'relative' }}>
        <img 
          src={url} 
          alt="AI Generated Output" 
          style={{ width: '100%', height: 'auto', display: 'block' }} 
        />
        <button 
          onClick={handleDownload}
          style={{ position: 'absolute', bottom: '1rem', right: '1rem', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(10px)', WebkitBackdropFilter: 'blur(10px)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '50%', width: '44px', height: '44px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', cursor: 'pointer', transition: 'all 0.2s' }}
          title="Save to Camera Roll / Download"
          onMouseOver={(e) => e.currentTarget.style.background = 'rgba(212,175,55,0.8)'}
          onMouseOut={(e) => e.currentTarget.style.background = 'rgba(0,0,0,0.6)'}
        >
          <Download size={20} />
        </button>
      </div>
    </div>
  )
}
