const GLOBAL_INVIOLABLE_RULES = `\n\n[GLOBAL RULES]\n- 1:1 PRODUCT FIDELITY: The generated image MUST preserve the original uploaded product EXACTLY. Do NOT add, remove, change, or invent logos, tags, patterns, seams, colors, or structural details. Only pose/scene changes. No watermarks. Remove store tags. Do NOT hallucinate inner labels. Open jackets must have a shirt underneath.\n- ANATOMY & GENDER: Human models must look hyper-realistic, natural, 18-50 years old, matching selected gender. NO plastic skin, CGI, extra limbs, or deformed hands. Model identity MUST stay identical across shots.\n- NO-MODEL OVERRIDE: If "No Model", NO human presence (no hands, reflections, mannequins) is allowed.\n- PHOTOGRAPHY STANDARD: Professional, cinematic optics (medium format), natural bokeh, film grain. NO hyper-digital smoothing. Fabric physics must be authentic (drape/folds match fabric type). Use soft directional lighting (Chiaroscuro). High-end global casting.\n- STUDIO CONSISTENCY: For studio shots, background color MUST remain EXACTLY identical. Use elegant neutrals (taupe, light grey, soft sand). STRICTLY FORBIDDEN: Pure white (#FFFFFF) or overexposed blown-out backgrounds.\n- ENVIRONMENTAL INTEGRATION: Perfect grounding, ambient occlusion, realistic contact shadows.`;
const productLockSystem = `\n[CRITICAL PRODUCT LOCK SYSTEM: The uploaded product image is the ONLY source of truth for the fabric and shape, but you MUST understand real swimwear construction. SWIMWEAR STRAP RULE: Flat-lay product images often show back-tie or neck-tie strings dangling down the middle. YOU MUST TIE THEM CORRECTLY BEHIND THE BACK OR BEHIND THE NECK. ABSOLUTELY NO loose strings, laces, or bows hanging from the front of the upper garment, in the center, or on the midsection. The lower straps go directly backwards under the armpits to tie at the back. DO NOT draw strings wrapping around the front midsection or criss-crossing the torso. The front torso must be clear of strings unless the design explicitly features a fixed front knot. PRIORITY: Realistic structural construction > flat-lay literal interpretation.]`;
const wearDirective = "\n[DIRECTIVE: The product must be displayed ALONE, flat lay or ghost mannequin. NO HUMAN MODEL.]";
const dynamicAestheticOverrides = `\n[GHOST MANNEQUIN CONSISTENCY RULE]: Professional ecommerce catalog photography. ABSOLUTELY NO HUMAN PRESENCE. The focus must remain entirely on the product. All backgrounds must use a clean solid color with a professional commercial look. The background MUST remain perfectly consistent across all images (exact same color tone, lighting setup, shadows). Simulate a single product photoshoot with identical lighting conditions. Lighting should be soft, controlled, and realistic to showcase textures. Only the camera angle, framing, and product orientation may vary. `;
const dynamicAestheticNegatives = "human presence, hands, body parts, reflections of people, silhouettes, mannequins, human interaction, ";
const swimwearNegative = "straps on midsection, laces on front midsection, strings around waist, criss-cross body strings, swimsuit strings on midsection, strings dangling from upper front, center upper front strings, loose front laces, hanging front strings, front knot, ";
let negativeDirective = swimwearNegative + dynamicAestheticNegatives;

let variantPrompt = `--- SWIMWEAR DYNAMIC GENERATION ---\n` + GLOBAL_INVIOLABLE_RULES + `\n` + productLockSystem + `\n` + wearDirective + `\n\n[DYNAMIC OVERRIDES & AESTHETICS]:\n\n` + `\n[CONTROLLED VARIATION SYSTEM: The environment, lighting, and model MUST remain identical across all generations. This is a single photoshoot. Do NOT change location, lighting direction/intensity, outfit, or model identity. Allowed variations ONLY in: camera angle, framing, and pose.]\n[MICRO VARIATION SYSTEM: Introduce subtle natural variations between shots: slight differences in facial expression, micro changes in body posture, minimal variation in hand positioning, and subtle shifts in gaze direction. These must feel natural and human, not staged.]\n[SHOOTING REALISM RULE: This must feel like a real photoshoot sequence. Avoid perfect symmetry. Avoid identical posture repetition. Avoid robotic consistency. Each image should feel like a different moment captured during the same shooting session.]\n[CAMERA VARIATION RULE: Each image MUST have a clearly different framing. For example, Image 1: full body (head to toe), strong presence; Image 2: mid shot (waist-up), natural and relatable; Image 3: close-up (torso or detail), emotional and aesthetic. Do NOT repeat the same framing. Each image must feel intentionally different in composition.]${dynamicAestheticOverrides}\n\n[SEED/VARIANTE: Generazione nr. 1.\nSTRICT CAMERA/POSE DIRECTIVE (YOU MUST FOLLOW THIS): [CLEAN CATALOG 1] Flat lay, clean studio background, perfect symmetry, perfect alignment\nLOCKED LIGHTING/AESTHETIC: soft and highly detailed\nMantieni il VISO PERFETTAMENTE A FUOCO e la FORMA/COLORE del capo identici all'originale.${negativeDirective}]`;

console.log("Variant prompt length: " + variantPrompt.length);
