const GLOBAL_INVIOLABLE_RULES = `\n\n[GLOBAL RULES]\n- 1:1 PRODUCT FIDELITY: The generated image MUST preserve the original uploaded product EXACTLY. Do NOT add, remove, change, or invent logos, tags, patterns, seams, colors, or structural details. Only pose/scene changes. No watermarks. Remove store tags. Do NOT hallucinate inner labels. Open jackets must have a shirt underneath.\n- ANATOMY & GENDER: Human models must look hyper-realistic, natural, 18-50 years old, matching selected gender. NO plastic skin, CGI, extra limbs, or deformed hands. Model identity MUST stay identical across shots.\n- NO-MODEL OVERRIDE: If "No Model", NO human presence (no hands, reflections, mannequins) is allowed.\n- PHOTOGRAPHY STANDARD: Professional, cinematic optics (medium format), natural bokeh, film grain. NO hyper-digital smoothing. Fabric physics must be authentic (drape/folds match fabric type). Use soft directional lighting (Chiaroscuro). High-end global casting.\n- STUDIO CONSISTENCY: For studio shots, background color MUST remain EXACTLY identical. Use elegant neutrals (taupe, light grey, soft sand). STRICTLY FORBIDDEN: Pure white (#FFFFFF) or overexposed blown-out backgrounds.\n- ENVIRONMENTAL INTEGRATION: Perfect grounding, ambient occlusion, realistic contact shadows.`;
const productLockSystem = `\n[CRITICAL PRODUCT LOCK SYSTEM: The uploaded product image is the ONLY source of truth. The AI must NOT reinterpret, redesign, or approximate the product. It must replicate: exact structure (shape, cuts, stitching, elasticity), exact top construction, exact strap positions and thickness, exact pattern placement and scale, exact fabric behavior, exact color tones. STRICT RULES: Do NOT simplify the design. Do NOT smooth or clean details. Do NOT change construction. Disable creative reinterpretation for the product. Apply creativity ONLY to: pose, background, camera. The straps MUST match exactly, the pattern MUST remain identical, all seams and proportions must match the original image. SWIMWEAR STRAP RULE: ABSOLUTELY NO STRAPS, LACES, OR STRINGS ON THE FRONT OF THE MODEL'S MIDSECTION OR WAIST. If the reference image shows loose strings or a bow hanging below the bikini top, DO NOT place the bow on the model's front midsection or lower ribcage. The lower straps go directly backwards under the armpits to tie at the back. DO NOT draw strings wrapping around the front midsection, waist, or criss-crossing the torso. THE FRONT MIDSECTION AND WAIST MUST BE COMPLETELY CLEAR AND FREE OF ANY STRINGS OR LACES. PRIORITY: Product accuracy > model > scene > aesthetics.]`;
const wearDirective = "\n[DIRECTIVE: The product must be displayed ALONE, flat lay or ghost mannequin. NO HUMAN PRESENCE.]";
const shotPositivePrompt = "A highly detailed ghost mannequin product photography shot of the swimwear...";
const shotNegativePrompt = "human, person, face, ";
const swimwearNegative = "straps on midsection, laces on front midsection, strings around waist, criss-cross body strings, swimsuit strings on midsection, ";
const negativeDirective = swimwearNegative + shotNegativePrompt;

let variantPrompt = `--- SWIMWEAR STATIC GENERATION (SHOT 1) ---\n` + GLOBAL_INVIOLABLE_RULES + productLockSystem + wearDirective + `\n\n[PROMPT DEFINITIVO]:\n${shotPositivePrompt}\n\n[HARD RULES DA RISPETTARE]:\nMust be perfect\n\n${negativeDirective}`;

console.log("Static prompt length: " + variantPrompt.length);
