import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import GalleryClient from "./GalleryClient";

export const metadata = {
  title: "AI Product Gallery | SuperNexus",
  description: "View ready-to-use product images generated by SuperNexus AI.",
};

export default async function GalleryPage({ params }: { params: { id: string } }) {
  const { id } = params;

  if (!id) {
    return notFound();
  }

  // Fetch the GenerationJob and related images
  const job = await prisma.generationJob.findUnique({
    where: { id },
    include: {
      images: {
        orderBy: { image_order: 'asc' }
      },
      subcategory: {
        include: {
          business_mode: {
            include: {
              category: true
            }
          }
        }
      }
    }
  });

  if (!job) {
    return notFound();
  }

  if (job.images.length === 0) {
    return (
      <div className="min-h-screen bg-[#050505] flex items-center justify-center text-white p-6">
        <div className="text-center space-y-4 max-w-md">
          <h1 className="text-3xl font-bold">Still Generating...</h1>
          <p className="text-zinc-400">
            The AI is currently processing this job. Please check back in a minute.
          </p>
        </div>
      </div>
    );
  }

  return (
    <GalleryClient 
      jobId={job.id}
      originalImage={job.original_product_image_url} 
      generatedImages={job.images} 
      styleName={job.subcategory?.name || "AI Generated"}
      categoryName={job.subcategory?.business_mode?.category?.name || "Product"}
    />
  );
}
